In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix
import os
os.chdir('D:\\Packt\\Bayesian Statistics\\Section 4\\Section four\\')

In [2]:
df = pd.read_csv('UCI_Credit_Card.csv')

In [3]:
df

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1    20000.0    2          2         1   24      2      2     -1   
1          2   120000.0    2          2         2   26     -1      2      0   
2          3    90000.0    2          2         2   34      0      0      0   
3          4    50000.0    2          2         1   37      0      0      0   
4          5    50000.0    1          2         1   57     -1      0     -1   
5          6    50000.0    1          1         2   37      0      0      0   
6          7   500000.0    1          1         2   29      0      0      0   
7          8   100000.0    2          2         2   23      0     -1     -1   
8          9   140000.0    2          3         1   28      0      0      2   
9         10    20000.0    1          3         2   35     -2     -2     -2   
10        11   200000.0    2          3         2   34      0      0      2   
11        12   260000.0    2          1         2   51     -1     -1     -1   
12        13   630000.0    2          2         2   41     -1      0     -1   
13        14    70000.0    1          2         2   30      1      2      2   
14        15   250000.0    1          1         2   29      0      0      0   
15        16    50000.0    2          3         3   23      1      2      0   
16        17    20000.0    1          1         2   24      0      0      2   
17        18   320000.0    1          1         1   49      0      0      0   
18        19   360000.0    2          1         1   49      1     -2     -2   
19        20   180000.0    2          1         2   29      1     -2     -2   
20        21   130000.0    2          3         2   39      0      0      0   
21        22   120000.0    2          2         1   39     -1     -1     -1   
22        23    70000.0    2          2         2   26      2      0      0   
23        24   450000.0    2          1         1   40     -2     -2     -2   
24        25    90000.0    1          1         2   23      0      0      0   
25        26    50000.0    1          3         2   23      0      0      0   
26        27    60000.0    1          1         2   27      1     -2     -1   
27        28    50000.0    2          3         2   30      0      0      0   
28        29    50000.0    2          3         1   47     -1     -1     -1   
29        30    50000.0    1          1         2   26      0      0      0   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29970  29971   360000.0    1          1         1   34     -1     -1     -1   
29971  29972    80000.0    1          3         1   36      0      0      0   
29972  29973   190000.0    1          1         1   37      0      0      0   
29973  29974   230000.0    1          2         1   35      1     -2     -2   
29974  29975    50000.0    1          2         1   37      1      2      2   
29975  29976   220000.0    1          2         1   41      0      0     -1   
29976  29977    40000.0    1          2         2   47      2      2      3   
29977  29978   420000.0    1          1         2   34      0      0      0   
29978  29979   310000.0    1          2         1   39      0      0      0   
29979  29980   180000.0    1          1         1   32     -2     -2     -2   
29980  29981    50000.0    1          3         2   42      0      0      0   
29981  29982    50000.0    1          2         1   44      1      2      2   
29982  29983    90000.0    1          2         1   36      0      0      0   
29983  29984    20000.0    1          2         1   44     -2     -2     -2   
29984  29985    30000.0    1          2         2   38     -1     -1     -2   
29985  29986   240000.0    1          1         2   30     -2     -2     -2   
29986  29987   360000.0    1          1         2   35     -1     -1     -2   
29987  29988   130000.0    1          1         2   34      0      0      0   
29988  29989   250000.0    1          1         1   34      

In [4]:
len(df)

30000

In [5]:
df.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
default      0
dtype: int64

In [6]:
x = df.iloc[:,0:24].values

In [7]:
x

array([[1.0000e+00, 2.0000e+04, 2.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.0000e+00, 1.2000e+05, 2.0000e+00, ..., 1.0000e+03, 0.0000e+00,
        2.0000e+03],
       [3.0000e+00, 9.0000e+04, 2.0000e+00, ..., 1.0000e+03, 1.0000e+03,
        5.0000e+03],
       ...,
       [2.9998e+04, 3.0000e+04, 1.0000e+00, ..., 4.2000e+03, 2.0000e+03,
        3.1000e+03],
       [2.9999e+04, 8.0000e+04, 1.0000e+00, ..., 1.9260e+03, 5.2964e+04,
        1.8040e+03],
       [3.0000e+04, 5.0000e+04, 1.0000e+00, ..., 1.0000e+03, 1.0000e+03,
        1.0000e+03]])

In [8]:
y = df.iloc[:,24].values

In [9]:
y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [10]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
x = sc_X.fit_transform(x)

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [12]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [13]:
y_pred = classifier.predict(x_test)

In [14]:
cm = confusion_matrix(y_test,y_pred)

In [15]:
cm

array([[2863, 1831],
       [ 378,  928]], dtype=int64)